# Configuration ULTRA-PERMISSIVE pour PME locales - CORRIGÉE

# Paramètres de traitement - ASSOUPLIS POUR PME
traitement:
  echantillon_test: 20
  periode_recherche_mois: 12  
  timeout_requetes_sec: 15    
  delai_entre_requetes_sec: 3 
  seuil_validation_minimum: 0.1  # ✅ ABAISSÉ de 0.45 à 0.1

# Paramètres de scoring - ULTRA-PERMISSIFS POUR PME
scoring:
  seuil_pertinence_minimum: 0.15  # ✅ ABAISSÉ de 0.4 à 0.15
  poids_source_officielle: 1.0
  poids_presse_locale: 0.9       
  poids_web_general: 0.7         
  bonus_recence: 0.3             
  bonus_source_multiple: 0.2     

# Paramètres validation ULTRA-ASSOUPLIS pour PME
validation:
  score_entreprise_minimum: 0.1  # ✅ ABAISSÉ de 0.4 à 0.1
  score_commune_bonus: 0.2       
  score_thematique_minimum: 0.05 # ✅ ABAISSÉ de 0.1 à 0.05
  exclusions_strictes: false     

# 📊 Seuils PME (ultra-permissifs)
seuils_pme:
  validation_minimum: 0.1    # ✅ ABAISSÉ de 0.45 à 0.1
  score_entreprise_minimum: 0.1  # ✅ COHÉRENT à 0.1

# Mots-clés ENRICHIS pour PME locales
mots_cles:
  recrutements:
    - "cherche"
    - "recherche" 
    - "recrute"
    - "embauche"
    - "offre emploi"
    - "apprenti"
    - "stagiaire"
    - "candidat"
    - "poste"
    
  evenements:
    - "ouverture"
    - "nouveau"
    - "inauguration"
    - "porte ouverte"
    - "événement"
    - "manifestation"
    - "salon"
    - "exposition"
    
  innovations:
    - "nouveau service"
    - "améliore"
    - "modernise"
    - "innovation"
    - "développe"
    - "rénove"
    - "équipe"
    - "investit"
    
  vie_entreprise:
    - "développement"
    - "expansion" 
    - "partenariat"
    - "ouverture"
    - "agrandit"
    - "déménage"
    - "reprend"
    - "installation"

# TERRITOIRE (gardé identique)
territoire:
  codes_postaux_cibles:
  - "77600"  # Bussy-Saint-Georges
  - "77700"  # Serris, Chessy, Coupvray
  - "77400"  # Lagny-sur-Marne
  - "77000"  # Melun
  - "77300"  # Fontainebleau
  - "77500"  # Chelles
  - "77200"  # Torcy
  - "77100"  # Meaux

communes_prioritaires:
  - "Bussy-Saint-Georges"
  - "Serris" 
  - "Chessy"
  - "Meaux"
  - "Melun"
  - "Chelles"
  - "Torcy"
  - "Lagny-sur-Marne"

# 🏢 Critères PME spécifiques (très permissifs)
filtrage_pme:
  effectif_max: 249
  secteurs_prioritaires:
    - "commerce"
    - "restauration"
    - "construction"
    - "services"
    - "artisanat"
    - "santé"
    - "transport"

# MOTEURS DE RECHERCHE (ordre de préférence)
search_engines_priority:
  1: "bing"
  2: "duckduckgo" 
  3: "yandex"
  4: "simulation"  # Fallback final