# 🔧 MODIFICATIONS À APPORTER DANS config/parametres.yaml

# Configuration ÉQUILIBRÉE pour PME locales - QUALITÉ RENFORCÉE

# Paramètres de traitement - RELEVÉS pour plus de qualité
traitement:
  echantillon_test: 20
  periode_recherche_mois: 12  
  timeout_requetes_sec: 15    
  delai_entre_requetes_sec: 3 
  seuil_validation_minimum: 0.3  # ✅ RELEVÉ de 0.1 à 0.3

# Paramètres de scoring - ÉQUILIBRÉS pour PME
scoring:
  seuil_pertinence_minimum: 0.4  # ✅ RELEVÉ de 0.15 à 0.4
  seuil_validation_url: 0.8      # URLs doivent être très fiables
  seuil_contenu_substantiel: 50
  poids_source_officielle: 1.0
  poids_presse_locale: 0.9       
  poids_web_general: 0.6         # ✅ RÉDUIT de 0.7 à 0.6
  bonus_recence: 0.2             # ✅ RÉDUIT de 0.3 à 0.2
  bonus_source_multiple: 0.15    # ✅ RÉDUIT de 0.2 à 0.15

# Paramètres validation ÉQUILIBRÉS pour PME
validation:
  score_entreprise_minimum: 0.25  # ✅ RELEVÉ de 0.1 à 0.25
  score_commune_bonus: 0.2       
  score_thematique_minimum: 0.2   # ✅ RELEVÉ de 0.05 à 0.2
  exclusions_strictes: true       # ✅ ACTIVÉ au lieu de false
  desactiver_simulation: true          # Désactive les simulations
  desactiver_enrichissement_insee: true  # Désactive enrichissement factice
  desactiver_donnees_sectorielles: true  # Désactive données sectorielles factices
  score_minimum_reel: 0.6             # Score minimum pour considérer contenu réel
  validation_urls_stricte: true

# 📊 Seuils PME (équilibrés)
seuils_pme:
  validation_minimum: 0.3      # ✅ RELEVÉ de 0.1 à 0.3
  score_entreprise_minimum: 0.25  # ✅ COHÉRENT à 0.25
  score_global_minimum: 0.2   # ✅ NOUVEAU seuil pour score global

# ❌ EXCLUSIONS STRICTES (nouveau)
exclusions:
  sites_non_pertinents:
    - "wikipedia.org"
    - "wordreference.com"
    - "dictionary.com"
    - "larousse.fr"
    - "reverso.net"
    - "linguee.com"
  
  contenu_non_pertinent:
    - "dictionnaire"
    - "traduction" 
    - "conjugaison"
    - "grammaire"
    - "cours de français"
    - "définition"
    - "forum.wordreference"

# ✅ EXCLUSIONS STRICTES
exclusions_contenu:
  mots_factices:
    - "information concernant"
    - "données contextuelles"
    - "activité économique locale"
    - "développement de l'activité"
    - "services aux habitants"
    - "contexte entreprise"
  
  urls_factices:
    - "exemple.fr"
    - "exemple-local.fr"
    - "test.fr"
    - "demo.fr"
    - "simulation.fr"
    - "salon-lagny-sur-marne.fr"

# Mots-clés AFFINÉS pour PME locales (qualité > quantité)
mots_cles:
  recrutements:
    - "recrute"        # Verbe actif
    - "embauche"       # Action concrète
    - "offre emploi"   # Annonce précise
    - "cherche"        # PME language
    - "CDI"           # Type contrat
    - "apprenti"      # PME spécifique
    
  evenements:
    - "ouverture"     # Action concrète
    - "inauguration"  # Événement réel
    - "porte ouverte" # PME classique
    - "nouveau"       # Changement
    - "événement"     # Générique mais utile
    
  innovations:
    - "nouveau service"  # PME scale innovation
    - "améliore"        # Amélioration continue
    - "modernise"       # Modernisation
    - "innovation"      # Terme direct
    - "développe"       # Développement
    
  vie_entreprise:
    - "développement"   # Croissance
    - "expansion"       # Extension
    - "partenariat"     # Collaboration
    - "ouverture"       # Nouvelle activité
    - "agrandit"        # Extension physique
    - "déménage"        # Changement local

# TERRITOIRE (inchangé)
territoire:
  codes_postaux_cibles:
  - "77600"  # Bussy-Saint-Georges
  - "77700"  # Serris, Chessy, Coupvray
  - "77400"  # Lagny-sur-Marne
  - "77000"  # Melun
  - "77300"  # Fontainebleau
  - "77500"  # Chelles
  - "77200"  # Torcy
  - "77100"  # Meaux

communes_prioritaires:
  - "Bussy-Saint-Georges"
  - "Serris" 
  - "Chessy"
  - "Meaux"
  - "Melun"
  - "Chelles"
  - "Torcy"
  - "Lagny-sur-Marne"

# 🏢 Critères PME équilibrés
filtrage_pme:
  effectif_max: 249
  secteurs_prioritaires:
    - "commerce"
    - "restauration"
    - "construction"
    - "services"
    - "artisanat"
    - "santé"
    - "transport"

# MOTEURS DE RECHERCHE (ordre de préférence)
search_engines_priority:
  1: "bing"
  2: "duckduckgo" 
  3: "yandex"
  4: "simulation"  # Fallback final désactivé par défaut

# ✅ NOUVEAUX PARAMÈTRES DE QUALITÉ
qualite:
  longueur_titre_minimum: 15        # Caractères minimum pour titre
  longueur_description_minimum: 30  # Caractères minimum pour description
  mots_business_requis: true        # Exiger mots business dans contenu
  validation_contenu_strict: true   # Validation stricte du contenu