# Configuration optimisée pour améliorer le taux de détection

# Paramètres de traitement - ASSOUPLIS
traitement:
  echantillon_test: 20
  periode_recherche_mois: 12  # Élargi à 12 mois
  timeout_requetes_sec: 15    # Augmenté pour plus de stabilité
  delai_entre_requetes_sec: 3 # Augmenté pour éviter les blocages
  seuil_validation_minimum: 0.2  # RÉDUIT de 0.3 à 0.2

# Paramètres de scoring - PLUS PERMISSIFS
scoring:
  seuil_pertinence_minimum: 0.2  # RÉDUIT
  poids_source_officielle: 1.0
  poids_presse_locale: 0.9       # AUGMENTÉ
  poids_web_general: 0.7         # AUGMENTÉ
  bonus_recence: 0.3             # AUGMENTÉ
  bonus_source_multiple: 0.2     # AUGMENTÉ

# Mots-clés ENRICHIS pour meilleure détection
mots_cles:
  recrutements:
    - "recrutement"
    - "recrute"
    - "embauche"
    - "offre emploi"
    - "offres emploi"
    - "CDI"
    - "CDD" 
    - "stage"
    - "alternance"
    - "apprentissage"
    - "carrière"
    - "poste"
    - "candidature"
    - "nous recherchons"
    - "rejoindre équipe"
    - "opportunité"
    
  evenements:
    - "événement"
    - "événements"
    - "porte ouverte"
    - "portes ouvertes"
    - "journée porte ouverte"
    - "conférence"
    - "salon"
    - "forum"
    - "rencontre"
    - "manifestation"
    - "colloque"
    - "séminaire"
    - "présentation"
    - "démonstration"
    - "inauguration"
    
  innovations:
    - "innovation"
    - "nouveau"
    - "nouveau produit"
    - "nouveau service"
    - "lancement"
    - "R&D"
    - "recherche développement"
    - "technologie"
    - "modernisation"
    - "amélioration"
    - "développement"
    - "créativité"
    - "avancée"
    - "progrès"
    
  vie_entreprise:
    - "développement"
    - "expansion"
    - "croissance"
    - "partenariat"
    - "collaboration"
    - "implantation"
    - "ouverture"
    - "installation"
    - "projet"
    - "investissement"
    - "stratégie"
    - "évolution"
    - "transformation"

# Stratégies de recherche MULTIPLES
strategies_recherche:
  prioritaires:
    - "nom_exact_thematique"      # "Entreprise XYZ" recrutement
    - "nom_commune_thematique"    # "Entreprise XYZ" Ville emploi
    - "mots_cles_commune"         # Mots-clés Ville secteur
    
  fallback:
    - "secteur_commune_thematique" # Secteur Ville thématique
    - "commune_thematique_generale" # Ville thématique générale

# Paramètres validation ASSOUPLIS
validation:
  score_entreprise_minimum: 0.2  # RÉDUIT de 0.5 à 0.3
  score_commune_bonus: 0.2       # Bonus si commune mentionnée
  score_thematique_minimum: 0.1  # RÉDUIT
  exclusions_strictes: false     # ASSOUPLI
  
# Sources autorisées ÉLARGIES
sources_autorisees:
  sites_entreprise: true
  presse_locale: true
  presse_nationale: true
  sites_institutionnels: true
  portails_emploi: true
  sites_sectoriels: true
  reseaux_sociaux: true          # AJOUTÉ
  forums_professionnels: false   # Gardé à false pour qualité

# 🎯 NOUVEAUTÉ : Votre territoire spécifique
territoire:
  codes_postaux_cibles:
    - "77600"  # Remplacez par VOS codes postaux
    - "77700"  
    - "77400"  # Ajoutez tous vos codes postaux
    - "77000"
    - "77058"
    - "77059"
    - "77062"
    - "77075"
    - "77085"
    - "77121"
    - "77124"
    - "77155"
    - "77181"
    - "77209"
    - "77221"
    - "77234"
    - "77237"
    - "77243"
    - "77248"
    - "77307"
    - "77372"
    - "77374"
    - "77438"
    - "77464"
    
  communes_prioritaires:
    - "Bussy-Saint-Georges"  # Vos communes
    - "Serris"
    - "Meaux"
    - "BUSSY SAINT MARTIN"
    - "CARNETIN"
    - "CHALIFERT"
    - "CHANTELOUP EN BRIE"
    - "COLLEGIEN"
    - "CONCHES SUR GONDOIRE"
    - "DAMPMART"
    - "FERRIERES EN BRIE"
    - "GOUVERNES"
    - "GUERMANTES"
    - "JABLINES"
    - "JOSSIGNY"
    - "LAGNY SUR MARNE"
    - "LESCHES"
    - "MONTEVRAIN"
    - "POMPONNE"
    - "PONTCARRE"
    - "SAINT THIBAULT DES VIGNES"
    - "THORIGNY SUR MARNE"
    
# 🏢 Critères PME spécifiques
filtrage_pme:
  effectif_max: 249
  secteurs_prioritaires:
    - "commerce"
    - "restauration"
    - "construction"
    - "services"
    - "artisanat"

# 📊 Seuils PME (plus permissifs)
seuils_pme:
  validation_minimum: 0.25    # Au lieu de 0.5
  score_entreprise_minimum: 0.2



# Configuration Google Search (PRUDENTE)
google_search:
  enabled: true                    # Activer Google
  priority: 4                      # Dernière priorité (après Bing, Yandex, DuckDuckGo)
  daily_limit: 50                  # Maximum 50 requêtes/jour
  min_delay_seconds: 30            # Minimum 30s entre requêtes
  smart_delays: true               # Délais adaptatifs selon succès
  block_on_detection: true         # Blocage auto si détection
  block_duration_hours: 2          # Durée blocage en cas de détection
  
  # Conditions d'activation
  activation_conditions:
    other_engines_failed: 3        # Si 3+ autres moteurs échouent
    min_quality_threshold: 2       # Si <2 résultats des autres moteurs
    enterprise_queries_only: true  # Seulement requêtes d'entreprise
  
  # Protection anti-détection
  protection:
    rotate_user_agents: true
    randomize_delays: true
    respect_rate_limits: true
    use_french_domain: true        # google.fr plus permissif
    limit_results_per_query: 8     # Moins suspect que 10+
    
# Ordre des moteurs (GOOGLE EN DERNIER)
search_engines_priority:
  1: "bing"           # Premier choix - stable et performant
  2: "yandex"         # Deuxième choix - bon backup
  3: "duckduckgo"     # Troisième choix - fiable
  4: "google"         # DERNIER RECOURS - efficace mais risqué
  5: "simulation"     # Fallback final

# Seuils de qualité par moteur
quality_thresholds:
  bing: 3             # Minimum 3 résultats pour valider
  yandex: 2           # Minimum 2 résultats
  duckduckgo: 2       # Minimum 2 résultats  
  google: 1           # Minimum 1 résultat (car dernier recours)
  
# Monitoring et alertes
monitoring:
  log_google_usage: true
  alert_on_blocks: true
  daily_reports: true