# Configuration optimisée pour améliorer le taux de détection

# Paramètres de traitement - ASSOUPLIS
traitement:
  echantillon_test: 20
  periode_recherche_mois: 12  # Élargi à 12 mois
  timeout_requetes_sec: 15    # Augmenté pour plus de stabilité
  delai_entre_requetes_sec: 3 # Augmenté pour éviter les blocages
  seuil_validation_minimum: 0.2  # RÉDUIT de 0.3 à 0.2

# Paramètres de scoring - PLUS PERMISSIFS
scoring:
  seuil_pertinence_minimum: 0.2  # RÉDUIT
  poids_source_officielle: 1.0
  poids_presse_locale: 0.9       # AUGMENTÉ
  poids_web_general: 0.7         # AUGMENTÉ
  bonus_recence: 0.3             # AUGMENTÉ
  bonus_source_multiple: 0.2     # AUGMENTÉ

# Mots-clés ENRICHIS pour meilleure détection
mots_cles:
  recrutements:
    - "recrutement"
    - "recrute"
    - "embauche"
    - "offre emploi"
    - "offres emploi"
    - "CDI"
    - "CDD" 
    - "stage"
    - "alternance"
    - "apprentissage"
    - "carrière"
    - "poste"
    - "candidature"
    - "nous recherchons"
    - "rejoindre équipe"
    - "opportunité"
    
  evenements:
    - "événement"
    - "événements"
    - "porte ouverte"
    - "portes ouvertes"
    - "journée porte ouverte"
    - "conférence"
    - "salon"
    - "forum"
    - "rencontre"
    - "manifestation"
    - "colloque"
    - "séminaire"
    - "présentation"
    - "démonstration"
    - "inauguration"
    
  innovations:
    - "innovation"
    - "nouveau"
    - "nouveau produit"
    - "nouveau service"
    - "lancement"
    - "R&D"
    - "recherche développement"
    - "technologie"
    - "modernisation"
    - "amélioration"
    - "développement"
    - "créativité"
    - "avancée"
    - "progrès"
    
  vie_entreprise:
    - "développement"
    - "expansion"
    - "croissance"
    - "partenariat"
    - "collaboration"
    - "implantation"
    - "ouverture"
    - "installation"
    - "projet"
    - "investissement"
    - "stratégie"
    - "évolution"
    - "transformation"

# Stratégies de recherche MULTIPLES
strategies_recherche:
  prioritaires:
    - "nom_exact_thematique"      # "Entreprise XYZ" recrutement
    - "nom_commune_thematique"    # "Entreprise XYZ" Ville emploi
    - "mots_cles_commune"         # Mots-clés Ville secteur
    
  fallback:
    - "secteur_commune_thematique" # Secteur Ville thématique
    - "commune_thematique_generale" # Ville thématique générale

# Paramètres validation ASSOUPLIS
validation:
  score_entreprise_minimum: 0.3  # RÉDUIT de 0.5 à 0.3
  score_commune_bonus: 0.2       # Bonus si commune mentionnée
  score_thematique_minimum: 0.1  # RÉDUIT
  exclusions_strictes: false     # ASSOUPLI
  
# Sources autorisées ÉLARGIES
sources_autorisees:
  sites_entreprise: true
  presse_locale: true
  presse_nationale: true
  sites_institutionnels: true
  portails_emploi: true
  sites_sectoriels: true
  reseaux_sociaux: true          # AJOUTÉ
  forums_professionnels: false   # Gardé à false pour qualité